#!/bin/bash

##to install
#copy to /etc/init.d/my-firewall
#sudo update-rc.d my-firewall defaults

### BEGIN INIT INFO
# Provides:          my-firewall
# Required-Start:    $local_fs
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: A simple firewall (blocks user:david from internet)
# Description:       
### END INIT INFO

set -e
PATH="/sbin:/bin:/usr/sbin:/usr/bin"

_tables(){
    iptables  "$@"
    ip6tables "$@"
}

_delete(){
    table=$1
    shift
    _tables -D $table "$@" 2>/dev/null || true
}

_rawadd(){
    table=$1
    shift
    _tables -I $table 1 "$@" 
}

_add(){
    _delete "$@"
    _rawadd "$@"
}

allow(){
    cmd=$1
    shift
    _$cmd _add "$@"
}

remove(){
    cmd=$1
    shift
    _$cmd _delete "$@"
}

_owner(){
    cmd="$1"
    user="$2"
    $cmd OUTPUT -m owner --uid-owner $user -j ACCEPT
}


## Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script my-firewall"

    ##allow proxies to talk on our behalf
    allow owner proxy
    allow owner dnsmasq
  
    ;;
  stop)
    echo "Stopping script my-firewall"
    remove owner proxy
    remove owner dnsmasq
    ;;
  *)
    echo "Usage: /etc/init.d/my-firewall {start|stop}"
    exit 1
    ;;
esac

exit 0
