#!/bin/bash

##to install
#copy to /etc/init.d/my-firewall
#sudo update-rc.d my-firewall defaults

### BEGIN INIT INFO
# Provides:          my-firewall
# Required-Start:    $local_fs
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: A simple firewall (blocks user:david from internet)
# Description:       
### END INIT INFO

PATH="/sbin:/bin:/usr/sbin:/usr/bin"

_tables(){
    iptables  "$@"
    ip6tables "$@"
}

_privUser() {
    _tables $1 OUTPUT $2 -m owner --uid-owner "$3" -j ACCEPT 
}

removePrivalagedUser(){
    _privUser "-D" "" "$1"  2>/dev/null || true
}

addPrivalagedUser(){
    removePrivalagedUser $1
    _privUser "-I" "1" "$1"
}


## Carry out specific functions when asked to by the system
case "$1" in
  "start" | "restart" | "reload" | "force-reload" )
    echo "Starting script my-firewall"

    ##allow proxies to talk on our behalf
    addPrivalagedUser proxy
    addPrivalagedUser dnsmasq
  
    ;;
  "stop")
    echo "Stopping script my-firewall"
    removePrivalagedUser proxy
    removePrivalagedUser dnsmasq
    ;;
  *)
    echo "Usage: /etc/init.d/my-firewall {start|stop}"
    exit 1
    ;;
esac

exit 0
