#!/bin/bash

set -e
PATH="/sbin:/bin:/usr/sbin:/usr/bin"
ThisDir="$(dirname $0)"

#lock down	
ufw --force reset
ufw enable
ufw default deny incoming
ufw default reject outgoing

##ssh	
ufw allow in SSH
ufw allow out SSH
ufw allow in 33936/tcp #local ssh

##bit torrent
ufw allow in Transmission
ufw allow out Transmission

#email
ufw allow out IMAP
ufw allow out SMTP

cp -f "$ThisDir"/my-firewall /etc/init.d
chmod u+x,+X /etc/init.d/my-firewall
/etc/init.d/my-firewall start

