#!/bin/bash

set -e 
PATH="/sbin:/bin:/usr/sbin:/usr/bin"
ThisDir="$(dirname $0)"

http=80
https=443
ftp=21

function allow {
  direction=$1
  hostname=$2
  proto=$3
  ports=$4
  addressType=$5

  echo -ne "$hostname" |
    xargs -i{} -n1  host -t $addressType  {} | 
    sed -nre "s/.*has (IPv6 )?address ([0-9a-f.:]+)$/\2/p" | 
    xargs -n1 -i{} ufw allow $direction proto "$proto" to {} port "$ports"
}

#lock down	
ufw --force reset
ufw enable
ufw default deny incoming
ufw default reject outgoing

##ssh	
ufw allow in SSH
ufw allow out SSH
ufw allow in 33936/tcp #local ssh
ufw allow out 59553/tcp #android ssh

##bit torrent
ufw allow in Transmission
ufw allow out Transmission

##package management
allow out ftp.uk.debian.org tcp $http,$https,$ftp A
allow out ftp.uk.debian.org tcp $http,$https,$ftp AAAA

##email
ufw allow out IMAP
ufw allow out SMTP

##gmail — gmail is ignoring proxy settings.
allow in mail.google.com tcp $http,$https A
allow in gmail.com       tcp $http,$https A


##teredo
#ufw allow out 3544/udp


##some hand crafted iptables
cp -f "$ThisDir"/my-firewall /etc/init.d
chmod u+x,+X /etc/init.d/my-firewall
/etc/init.d/my-firewall start

